server:
  port: 8080

spring:
  main:
    web-application-type: servlet

  datasource:
    url: jdbc:mysql://localhost:3306/accesscontrol?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.batch_versioned_data: true
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 50

jwt:
  secret: mySuperSecureSecretKey1234567890!

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  file:
    name: logs/accesscontrol.log
