spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accesscontrol?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySuperSecureSecretKey1234567890!

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

